# Generated by Django 2.2 on 2019-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1)),
                ('submit', models.CharField(max_length=100)),
                ('custom', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text=" Example: '447480924803'", max_length=20)),
                ('content', models.TextField(help_text=" Example: 'Thanks ?'")),
                ('in_number', models.CharField(help_text=" Example: '447537402499'", max_length=20)),
                ('submit', models.CharField(help_text=" Example: 'Submit'", max_length=100)),
                ('network', models.CharField(help_text=" Example:  ''", max_length=20)),
                ('email', models.CharField(help_text=" Example: 'none'", max_length=20)),
                ('keyword', models.CharField(help_text=" Example:  ''", max_length=20)),
                ('comments', models.TextField(help_text=" Example: 'Thanks ?'")),
                ('credits', models.CharField(blank=True, help_text=" Example: '52'", max_length=20, null=True)),
                ('msg_id', models.CharField(help_text=" Example: '99173112889'", max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('received', models.DateTimeField(help_text=" Example: '2019-04-20 20:13:32'")),
                ('firstname', models.CharField(help_text=" Example: 'Jay'", max_length=100)),
                ('lastname', models.CharField(help_text=" Example: 'Jagpal'", max_length=100)),
                ('custom1', models.CharField(help_text=" Example:  ''", max_length=255)),
                ('custom2', models.CharField(help_text=" Example:  ''", max_length=255)),
                ('custom3', models.CharField(help_text=" Example:  ''", max_length=255)),
            ],
        ),
    ]
